
"""
for loop is like foreach loop in other tech
we rely on a collection that is generated by the function range
"""

for i in range(1, 30):
    # if i > 25:
    #     break                   # terminate the loop
    if i % 2 == 1:
        continue                # skip the iteration
    print(i, end=" ")
else:
    print("\nIterations completed successfully.....")

